### ISSUE TITLE
How to use custom ControlFilter in shiro-spring-boot？

### ISSUE THREAD

**Issue by fantasy0v0** [bdemers/shiro-spring-boot-example#2]
my code 
```java
@Configuration
@AutoConfigureBefore(ShiroWebFilterConfiguration.class)
public class ShiroConfiguration {

  @Bean
  public CustomControlFilter customControlFilter() {
    return new CustomControlFilter();
  }

  @Bean
  public ShiroFilterChainDefinition shiroFilterChainDefinition() {
      DefaultShiroFilterChainDefinition chainDefinition = new DefaultShiroFilterChainDefinition();
      // use permissive to NOT require authentication, our controller Annotations will decide that
      chainDefinition.addPathDefinition("/**", "customControlFilter");
      return chainDefinition;
    }
}
```

Exception:
Caused by: java.lang.IllegalArgumentException: There is no filter with name 'customControlFilter' to apply to chain [/**] in the pool of available Filters.  Ensure a filter with that name/path has first been registered with the addFilter method(s).

**Comment by bdemers** [comment]
Take a look at javadoc for [`ShiroFilterFactoryBean`](https://github.com/apache/shiro/blob/master/support/spring/src/main/java/org/apache/shiro/spring/web/ShiroFilterFactoryBean.java)

**Comment by fantasy0v0** [comment]
thanks，I thought I didn't need to override ShiroFilterFactoryBean。
